### ISSUE TITLE
Example Usage Needed for extract_style.py

### ISSUE THREAD

**Issue by pegahs1993** [DiffPoseTalk/DiffPoseTalk#22]
...

**Comment by GrigorySamokhin** [comment]
Hello @pegahs1993, have you find out how to run extract_style.py?

**Comment by xsyseu** [comment]
> Hello [@pegahs1993](https://github.com/pegahs1993), have you find out how to run extract_style.py?

I have the same question

**Comment by hugleecool** [comment]
I have same question, VHAP .npz not fit DiffPoseTalk. @xsyseu @GrigorySamokhin @pegahs1993 How you sovle?
