### ISSUE TITLE
Good results! Looking for code and dataset release.

### ISSUE THREAD

**Issue by Turlan** [DiffPoseTalk/DiffPoseTalk#3]

**Comment by johndpope** [comment]
![Screenshot from 2024-04-21 14-19-56](https://github.com/DiffPoseTalk/DiffPoseTalk/assets/289994/2065e127-c488-40ec-93c2-130fee00b260)

Microsoft is referencing this paper for VASA-1

any open sourcing of this would be much appreciated.

**Comment by RainEggplant** [comment]
Hi! Our code and dataset have been released. Please have a try!
