### ISSUE TITLE
POSE problem

### ISSUE THREAD

**Issue by 19010464** [DiffPoseTalk/DiffPoseTalk#9]
Hi,
Nice work !
I try your code to do inference following the instruction:
 `python demo.py --exp_name head-SA-hubert-WM --iter 110000 -a demo/input/audio/FAST.flac -c demo/input/coef/TH217.npy demo/input/style/TH217.npy -o TH217-FAST-TH217.mp4 -n 3 -ss 3 -sa 1.15 -dtr 0.99`
I do not change any code and use the pretrained model you provide, the Visual result shows the movements of head and jaw are very violent. I check the result coef_dict and found 'shape' and 'exp' parameters seems good but 'pose' parameters have large numerical variation(-5 to 5). change another pretrain model or style or input audio result same problem.
Did I do anything wrong?

**Comment by 19010464** [comment]
I reinstall the environment and redownload pretrain model and anything goes fine.

**Comment by passerby-cjl** [comment]
In my case, it is something to do with `coef_stats` argument. If it is set to `None`, violent movements of head and jaw will occur because of incorrect normalization.
